### ISSUE TITLE
Docs for default value of options.errorStack do not match code

### ISSUE THREAD

**Issue by jkehres** [AntonBazhal/lambda-handler-as-promised#16]
Docs in README say default value for `options.errorStack` is true but no code ever sets the value to true. The default value of `options.errorStack` is actually `undefined`, a falsly value, meaning `utils.sanitizeError()` will strip the stack trace by default.

**Comment by jkehres** [comment]
One solution is to update the docs to reflect the actual behaviour. The second is to change the behaviour so the stack trace is included by default. My preference is the latter.

**Comment by AntonBazhal** [comment]
Good point. I'll update docs and leave current behaviour, at least for now, because:
1. I don't want to introduce breaking change
2. It is safer to remove stack by default to prevent accidental leak of sensitive data

**Comment by zommerfelds** [comment]
I can understand your second point, but since Lambda logs exceptions by default (as do most other libraries/frameworks I know of) it would be nice to have that behaviour as well. It would probably help many developers debugging their code and would barely introduce any privacy issues because 1) the programmer should already have the responsibility of not logging anything sensitive and 2) the stacktrace goes to CloudWatch and not everyone usually has access to that. If the programmer doesn't want that then he can always disable the stack trace here. Just my 2 cents.

**Comment by AntonBazhal** [comment]
@zommerfelds It is not about logging. It removes stack trace from unhandled rejections before returning them to a user.

**Comment by zommerfelds** [comment]
By user you mean the caller of `lambda-handler-as-promised`? Wouldn't that be AWS Lambda? When we go check our logs on CloudWatch we get an empty stack trace (`[]`).

We use it as:
```
module.exports.handler= lambdaHandler((event, context) => {
  // stuff
});
```

**Comment by AntonBazhal** [comment]
Yes user = caller, but caller is not AWS Lambda. Caller is a whatever system that uses your lambda. If you actually need stack trace, just set `errorStack` to `true`.

**Comment by zommerfelds** [comment]
I see, you are probably talking about what data the Lambda instance returns. Most of our Lambdas are called by AWS or asynchronously (e.g. Kinesis, S3), so we don't use the return data. Anyway, I'm just saying that by using this default setting we get no stack traces in our logs, so we're gonna have to manually set `errorStack` to `true` on all our Lambdas.

**Comment by zommerfelds** [comment]
Maybe a good trade-off would be to log the stack trace in the default error hook, but return the sanitized  (without stack trace) version to the caller?

**Comment by AntonBazhal** [comment]
`lambda-handler-as-promised` does not log anything as this can introduce way more serious security issues. You, as a developer, can define whatever behaviour you need by overriding config values and/or providing hooks.

**Comment by zommerfelds** [comment]
AWS Lambda logs exception to CloudWatch by default, so I was just using that as a reference. But I get your point. Thanks for the comments :)
