### ISSUE TITLE
Invalid JavaScript?

### ISSUE THREAD

**Issue by zommerfelds** [AntonBazhal/lambda-handler-as-promised#6]
Hi, inside the README, you have the following code:

`if (result) ? return result : throw new Error('Winter is coming!');`

Is this valid JavaScript? It doesn't seem so to me, by I'm not an expert.

Cheers

**Comment by AntonBazhal** [comment]
Hi, @zommerfelds. It's definitely not. Thanks for noticing this.

**Comment by AntonBazhal** [comment]
Closed by #7
